"""
Blockchain service — web3 integration with Quest 1 smart contracts.
Calls TokenizedDeposit, ReserveOracle, and CariSettlement on ZKsync Prividium.

Cari Deposit Account (CDA) = on-chain representation of a Demand Deposit Account (DDA).
DDA <-> CDA flow: fiat in DDA triggers CDA mint; CDA burn triggers fiat back to DDA.

the Issuing Bank | Cari Network | ZKsync Prividium.

SECURITY GUARDIAN NOTE:
- In production, signing uses AWS CloudHSM / Azure Key Vault via the HSM adapter.
- Private keys in config are LOCAL-DEV-ONLY and MUST be empty in production.
- Separation of duties: minter key != attestor key != compliance key.

Per Cari Whitepaper: the Operator (the Issuing Bank) is the single entity controlling
CDA supply — authorized to mint (DDA->CDA) and burn (CDA->DDA). The Operator
address is configured via Settings and its signing key is managed by HSM in production.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Optional

try:
    from eth_account import Account
    from web3 import AsyncWeb3, AsyncHTTPProvider
    from web3.contract import AsyncContract
    from web3.types import TxReceipt
    HAS_WEB3 = True
except ImportError:
    HAS_WEB3 = False
    Account = None  # type: ignore[assignment, misc]
    AsyncWeb3 = None  # type: ignore[assignment, misc]
    AsyncHTTPProvider = None  # type: ignore[assignment, misc]
    AsyncContract = None  # type: ignore[assignment, misc]
    TxReceipt = dict  # type: ignore[assignment, misc]

from offchain.config import Settings, get_settings
from offchain.services import audit

logger = logging.getLogger("cari.blockchain")

# ABI paths (generated by `forge build` in out/)
_ABI_DIR = Path(__file__).resolve().parent.parent.parent / "out"

_TOKEN_ABI_PATH = _ABI_DIR / "TokenizedDeposit.sol" / "TokenizedDeposit.json"
_ORACLE_ABI_PATH = _ABI_DIR / "ReserveOracle.sol" / "ReserveOracle.json"
_SETTLEMENT_ABI_PATH = _ABI_DIR / "CariSettlement.sol" / "CariSettlement.json"


def _load_abi(path: Path) -> list[dict]:
    """Load ABI from Foundry build output."""
    if not path.exists():
        logger.warning("ABI file not found: %s — using empty ABI", path)
        return []
    data = json.loads(path.read_text())
    return data.get("abi", [])


class BlockchainService:
    """Async service for interacting with Quest 1 CDA contracts on ZKsync Prividium."""

    def __init__(self, settings: Settings | None = None) -> None:
        self._settings = settings or get_settings()
        self._w3: AsyncWeb3 | None = None
        self._token: AsyncContract | None = None
        self._oracle: AsyncContract | None = None
        self._settlement: AsyncContract | None = None

    async def connect(self) -> None:
        """Initialize web3 connection and contract instances."""
        s = self._settings
        self._w3 = AsyncWeb3(AsyncHTTPProvider(s.prividium_rpc_url))
        connected = await self._w3.is_connected()
        logger.info("ZKsync Prividium connected: %s (rpc=%s)", connected, s.prividium_rpc_url)

        if s.token_contract_address:
            self._token = self._w3.eth.contract(
                address=self._w3.to_checksum_address(s.token_contract_address),
                abi=_load_abi(_TOKEN_ABI_PATH),
            )
        if s.oracle_contract_address:
            self._oracle = self._w3.eth.contract(
                address=self._w3.to_checksum_address(s.oracle_contract_address),
                abi=_load_abi(_ORACLE_ABI_PATH),
            )
        if s.settlement_contract_address:
            self._settlement = self._w3.eth.contract(
                address=self._w3.to_checksum_address(s.settlement_contract_address),
                abi=_load_abi(_SETTLEMENT_ABI_PATH),
            )

    @property
    def is_connected(self) -> bool:
        return self._w3 is not None

    # =========================================================================
    #                        TOKEN OPERATIONS
    # =========================================================================

    async def mint(
        self, *, to: str, amount: int, reference_id: str
    ) -> str:
        """Mint Cari deposits (CDA). Returns tx hash.

        Caller: MINTER_ROLE (HSM-backed in production).
        """
        assert self._token is not None, "Token contract not initialized"
        tx = await self._build_and_send(
            self._token.functions.mint(
                self._w3.to_checksum_address(to), amount, reference_id
            ),
            signer_key=self._settings.minter_private_key,
        )
        await audit.record(
            actor="MINTER_ROLE",
            action="mint",
            resource="TokenizedDeposit",
            details={"to": to, "amount": amount, "reference_id": reference_id, "tx_hash": tx},
        )
        return tx

    async def burn(
        self, *, from_addr: str, amount: int, reference_id: str
    ) -> str:
        """Burn Cari deposits (CDA) for par redemption (CDA->DDA). Returns tx hash."""
        assert self._token is not None
        tx = await self._build_and_send(
            self._token.functions.burn(
                self._w3.to_checksum_address(from_addr), amount, reference_id
            ),
            signer_key=self._settings.burner_private_key,
        )
        await audit.record(
            actor="BURNER_ROLE",
            action="burn",
            resource="TokenizedDeposit",
            details={"from": from_addr, "amount": amount, "reference_id": reference_id, "tx_hash": tx},
        )
        return tx

    async def total_supply(self) -> int:
        """Read current total supply of cUSD."""
        assert self._token is not None
        return await self._token.functions.totalSupply().call()

    async def balance_of(self, address: str) -> int:
        assert self._token is not None
        return await self._token.functions.balanceOf(
            self._w3.to_checksum_address(address)
        ).call()

    async def is_whitelisted(self, address: str) -> bool:
        assert self._token is not None
        return await self._token.functions.isWhitelisted(
            self._w3.to_checksum_address(address)
        ).call()

    async def is_frozen(self, address: str) -> bool:
        assert self._token is not None
        return await self._token.functions.isFrozen(
            self._w3.to_checksum_address(address)
        ).call()

    # =========================================================================
    #                       RESERVE ORACLE
    # =========================================================================

    async def get_total_reserves(self) -> int:
        """Read total reserves from ReserveOracle (6-decimal USD)."""
        assert self._oracle is not None
        return await self._oracle.functions.totalReserves().call()

    async def is_attestation_fresh(self) -> bool:
        assert self._oracle is not None
        return await self._oracle.functions.isAttestationFresh().call()

    async def get_attestation_hash(self) -> bytes:
        assert self._oracle is not None
        return await self._oracle.functions.attestationHash().call()

    async def can_mint(self, current_supply: int, mint_amount: int) -> bool:
        assert self._oracle is not None
        return await self._oracle.functions.canMint(current_supply, mint_amount).call()

    async def update_attestation(
        self, total_reserves: int, attestation_hash: bytes
    ) -> str:
        """Submit a new reserve attestation. Caller: ATTESTOR_ROLE (HSM-backed)."""
        assert self._oracle is not None
        tx = await self._build_and_send(
            self._oracle.functions.updateAttestation(total_reserves, attestation_hash),
            signer_key=self._settings.attestor_private_key,
        )
        await audit.record(
            actor="ATTESTOR_ROLE",
            action="update_attestation",
            resource="ReserveOracle",
            details={"total_reserves": total_reserves, "tx_hash": tx},
        )
        return tx

    # =========================================================================
    #                       CARI SETTLEMENT
    # =========================================================================

    async def initiate_settlement(
        self,
        *,
        destination_bank: str,
        originator: str,
        beneficiary: str,
        amount: int,
        travel_rule_hash: bytes,
    ) -> str:
        """Initiate cross-bank CDA settlement (burn CDA at source). Returns tx hash."""
        assert self._settlement is not None
        tx = await self._build_and_send(
            self._settlement.functions.initiateSettlement(
                self._w3.to_checksum_address(destination_bank),
                self._w3.to_checksum_address(originator),
                self._w3.to_checksum_address(beneficiary),
                amount,
                travel_rule_hash,
            ),
            signer_key=self._settings.settlement_private_key,
        )
        await audit.record(
            actor="INITIATOR_ROLE",
            action="initiate_settlement",
            resource="CariSettlement",
            details={
                "destination_bank": destination_bank,
                "originator": originator,
                "beneficiary": beneficiary,
                "amount": amount,
                "tx_hash": tx,
            },
        )
        return tx

    # =========================================================================
    #                       INTERNALS
    # =========================================================================

    async def _build_and_send(
        self, fn, *, signer_key: str
    ) -> str:
        """Build, sign, and send a transaction. Returns tx hash hex."""
        assert self._w3 is not None
        if not signer_key:
            raise RuntimeError(
                "No signing key configured. In production, use HSM. "
                "For local dev, set the appropriate CARI_*_PRIVATE_KEY env var."
            )
        account = Account.from_key(signer_key)
        nonce = await self._w3.eth.get_transaction_count(account.address)
        tx = await fn.build_transaction({
            "from": account.address,
            "nonce": nonce,
            "chainId": self._settings.chain_id,
        })
        signed = self._w3.eth.account.sign_transaction(tx, signer_key)
        tx_hash = await self._w3.eth.send_raw_transaction(signed.raw_transaction)
        hex_hash = tx_hash.hex()
        logger.info("TX sent: %s (signer=%s)", hex_hash, account.address)
        return hex_hash

    async def wait_for_receipt(self, tx_hash: str, timeout: int = 120) -> dict:
        """Wait for transaction confirmation."""
        assert self._w3 is not None
        receipt = await self._w3.eth.wait_for_transaction_receipt(tx_hash, timeout=timeout)
        return dict(receipt)


def get_operator_address() -> str:
    """Return the configured Operator address for CDA supply management.
    
    Per Cari Whitepaper: the Operator is the Issuing Bank's centralized entity
    authorized to control mint/burn of Cari Deposit Accounts (CDA).
    """
    settings = get_settings()
    if not settings.operator_address:
        raise ValueError("Operator address not configured — set OPERATOR_ADDRESS in environment")
    return settings.operator_address


# Singleton
_blockchain_service: BlockchainService | None = None


def get_blockchain_service() -> BlockchainService:
    global _blockchain_service
    if _blockchain_service is None:
        _blockchain_service = BlockchainService()
    return _blockchain_service
